name: Xtrem-craft-workflow

on:
  push:
    branches:
      - '*' # Push to all branches
      - '!gh-pages' # Exclude gh-pages
    paths:
      - "php/**" # Only run on changes within the php directory
      - ".github/workflows/xtrem.yml" # Only run on changes to the workflow file
      - "gh-pages" # Only run for modify the github pages branch
  pull_request:
    branches: [ "main" ]
    paths:
      - "php/**" # Only run on changes within the php directory
      - ".github/workflows/xtrem.yml" # Only run on changes to the workflow file
      - "gh-pages" # Only run for modify the github pages branch

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./php

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check for tests
      run: vendor/bin/phpunit --colors=always --testdox

    - name: Check for infection
      run: vendor/bin/infection --threads=4 --show-mutations --logger-html='mutation-report.html'
      # --min-msi=95 --min-covered-msi=95 --only-covered

    - name: Upload mutation report
      uses: actions/upload-artifact@v3
      with:
          name: mutation-report
          path: /home/runner/work/xtrem-craft-workshop/xtrem-craft-workshop/php/mutation-report.html
  
  gh-pages:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJSON(github) }}
      #   run: echo "$GITHUB_CONTEXT"

      # - name: Download build artifact from triggered workflow
      #   uses: dawidd6/action-download-artifact@v2.28.0
      #   with:
      #     workflow: "xtrem.yml"
      #     # run_id: ${{ github.run_id }}
      #     workflow_conclusion: ""
      #     path: ./artifacts
      #     #search_artifacts: true


      - name: checkout with all html
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git fetch
          git checkout origin/gh-pages
          git pull origin gh-pages --force
          tree
          git checkout master gh-pages/index.html
          git reset HEAD
          mv gh-pages/* .
          mv artifacts/mutation-report/mutation-report.html mutation-report.html
          git add index.html mutation-report.html
          [[ -n $(git status -s) ]] && git commit -m "Update index.html and mutation-report.html" || echo "No changes to commit"
        # git checkout master php/mutation-report.html
        # mv php/mutation-report.html mutation-report.html

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages