name: PHP Composer

on:
  push:
    branches:
      - '*' # Push to all branches
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./php

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check for tests
      run: vendor/bin/phpunit --colors=always --testdox

    - name: Check for infection
      run: vendor/bin/infection --threads=4 --show-mutations --logger-html='mutation-report.html'
      # --min-msi=95 --min-covered-msi=95 --only-covered

    - name: Upload mutation report
      uses: actions/upload-artifact@v2
      with:
          name: mutation-report
          path: mutation-report.html
